"""Extract the tuning-relevant parameters from a full .param dump into a grouped file.

  fc_param_pid.py FULL.param OUT.param

Output keeps the `NAME,VALUE` format (loadable in Mission Planner) but adds `#` section
headers, so it can be read as a tuning reference for a similar airframe. Anything not in
GROUPS below is dropped — this is a reference, not a backup; the backup is the full dump.
"""
import sys

# (section title, [exact names or NAME* prefixes])
GROUPS = [
    ("Airframe / motors - read these first, the rest only makes sense with them", [
        "FRAME_CLASS", "FRAME_TYPE", "MOT_PWM_TYPE", "MOT_PWM_MIN", "MOT_PWM_MAX",
        "MOT_SPIN_ARM", "MOT_SPIN_MIN", "MOT_SPIN_MAX", "MOT_THST_EXPO", "MOT_THST_HOVER",
        "MOT_HOVER_LEARN", "MOT_BAT_VOLT_MAX", "MOT_BAT_VOLT_MIN", "MOT_BAT_CURR_MAX",
        "MOT_YAW_HEADROOM", "MOT_THST_HOVER", "SCHED_LOOP_RATE", "INS_GYRO_RATE",
    ]),
    ("Rate PIDs - roll", ["ATC_RAT_RLL_*"]),
    ("Rate PIDs - pitch", ["ATC_RAT_PIT_*"]),
    ("Rate PIDs - yaw", ["ATC_RAT_YAW_*"]),
    ("Angle P + attitude shaping", [
        "ATC_ANG_RLL_P", "ATC_ANG_PIT_P", "ATC_ANG_YAW_P", "ATC_ANG_LIM_TC",
        "ATC_ACCEL_R_MAX", "ATC_ACCEL_P_MAX", "ATC_ACCEL_Y_MAX",
        "ATC_RATE_R_MAX", "ATC_RATE_P_MAX", "ATC_RATE_Y_MAX",
        "ATC_INPUT_TC", "ATC_SLEW_YAW", "ATC_THR_MIX_MIN", "ATC_THR_MIX_MAN",
        "ATC_THR_MIX_MAX", "ATC_RAT_RLL_SMAX", "ANGLE_MAX", "PILOT_Y_RATE",
    ]),
    ("Gyro / accel filtering", [
        "INS_GYRO_FILTER", "INS_ACCEL_FILTER", "INS_FAST_SAMPLE",
    ]),
    ("Harmonic notch (vibration) - tune before the PIDs", ["INS_HNTCH_*", "INS_HNTC2_*"]),
    ("Position / velocity controller (Loiter, Auto, Land)", ["PSC_*"]),
    ("Navigation speeds and accelerations", [
        "WPNAV_*", "LOIT_*", "PILOT_SPEED_UP", "PILOT_SPEED_DN", "PILOT_ACCEL_Z",
        "LAND_SPEED", "LAND_SPEED_HIGH", "LAND_ALT_LOW",
    ]),
    ("Autotune", ["AUTOTUNE_*"]),
    ("Battery compensation of the PIDs", ["MOT_BAT_*", "BATT_ARM_VOLT", "BATT_LOW_VOLT"]),
]


def matches(name, pats):
    for p in pats:
        if p.endswith("*") and name.startswith(p[:-1]):
            return True
        if name == p:
            return True
    return False


def main(src, out):
    params = {}
    for line in open(src, encoding="ascii"):
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        k, _, v = line.partition(",")
        params[k.strip()] = v.strip()

    used = set()
    with open(out, "w", encoding="ascii") as f:
        f.write("# ArduPilot tuning reference - extracted from %s\n"
                "# Subset only (PID / filter / controller parameters); the full backup is the\n"
                "# source file. Generated by tools/fc_param_pid.py.\n" % src.replace("\\", "/"))
        for title, pats in GROUPS:
            sel = sorted(k for k in params if matches(k, pats) and k not in used)
            if not sel:
                continue
            used.update(sel)
            f.write("\n# ---- %s\n" % title)
            for k in sel:
                f.write("%s,%s\n" % (k, params[k]))
    print("wrote %s: %d of %d parameters" % (out, len(used), len(params)))


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
